// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the accounts methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `ModelListParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelListParams {
    /// Opaque pagination cursor returned by a previous call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// When true, include models that are hidden from the default picker list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_hidden: Option<bool>,
    /// Optional page size; defaults to a reasonable server-side value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

/// `ModelAvailabilityNux`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelAvailabilityNux {
    /// `message`.
    pub message: String,
}

/// Canonical user-input modality tags advertised by a model.
pub type InputModality = crate::agents::codex::tolerant::Tolerant<InputModalityKnown>;

/// The variants of `InputModality` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum InputModalityKnown {
    /// Plain text turns and tool payloads.
    #[serde(rename = "text")]
    Text,
    /// Image attachments included in user turns.
    #[serde(rename = "image")]
    Image,
    /// Audio attachments included in user turns.
    #[serde(rename = "audio")]
    Audio,
}

/// `ModelServiceTier`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelServiceTier {
    /// `description`.
    pub description: String,
    /// `id`.
    pub id: String,
    /// `name`.
    pub name: String,
}

/// `ReasoningEffortOption`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasoningEffortOption {
    /// `description`.
    pub description: String,
    /// `reasoningEffort`.
    pub reasoning_effort: ReasoningEffort,
}

/// `ModelUpgradeInfo`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelUpgradeInfo {
    /// `migrationMarkdown`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub migration_markdown: Option<String>,
    /// `model`.
    pub model: String,
    /// `modelLink`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_link: Option<String>,
    /// `upgradeCopy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upgrade_copy: Option<String>,
}

/// `Model`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Model {
    /// Deprecated: use `serviceTiers` instead.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_speed_tiers: Option<Vec<String>>,
    /// `availabilityNux`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub availability_nux: Option<ModelAvailabilityNux>,
    /// `defaultReasoningEffort`.
    pub default_reasoning_effort: ReasoningEffort,
    /// Catalog default service tier id for this model, when one is configured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_service_tier: Option<String>,
    /// `description`.
    pub description: String,
    /// `displayName`.
    pub display_name: String,
    /// `hidden`.
    pub hidden: bool,
    /// `id`.
    pub id: String,
    /// `inputModalities`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_modalities: Option<Vec<InputModality>>,
    /// `isDefault`.
    pub is_default: bool,
    /// `model`.
    pub model: String,
    /// `modelSpecialty`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_specialty: Option<String>,
    /// `serviceTiers`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tiers: Option<Vec<ModelServiceTier>>,
    /// `supportedReasoningEfforts`.
    pub supported_reasoning_efforts: Vec<ReasoningEffortOption>,
    /// `supportsPersonality`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub supports_personality: Option<bool>,
    /// `upgrade`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upgrade: Option<String>,
    /// `upgradeInfo`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upgrade_info: Option<ModelUpgradeInfo>,
}

/// `ModelListResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelListResponse {
    /// `data`.
    pub data: Vec<Model>,
    /// Opaque cursor to pass to the next call to continue after the last item. If None, there are no more items to return.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// `SkillsListParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillsListParams {
    /// When empty, defaults to the current session working directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwds: Option<Vec<String>>,
    /// When true, bypass the skills cache and re-scan skills from disk.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force_reload: Option<bool>,
}

/// `SkillErrorInfo`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillErrorInfo {
    /// `message`.
    pub message: String,
    /// `path`.
    pub path: String,
}

/// `SkillToolDependency`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillToolDependency {
    /// `command`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// `description`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// `transport`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transport: Option<String>,
    /// `type`.
    pub r#type: String,
    /// `url`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// `value`.
    pub value: String,
}

/// `SkillDependencies`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillDependencies {
    /// `tools`.
    pub tools: Vec<SkillToolDependency>,
}

/// `SkillInterface`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillInterface {
    /// `brandColor`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub brand_color: Option<String>,
    /// `defaultPrompt`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default_prompt: Option<String>,
    /// `displayName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// `iconLarge`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_large: Option<AbsolutePathBuf>,
    /// Remote large icon URL from the plugin catalog.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_large_url: Option<String>,
    /// `iconSmall`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_small: Option<AbsolutePathBuf>,
    /// Remote small icon URL from the plugin catalog.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon_small_url: Option<String>,
    /// `shortDescription`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
}

/// `SkillScope`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SkillScope {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "repo")]
    Repo,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "admin")]
    Admin,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `SkillMetadata`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillMetadata {
    /// `dependencies`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dependencies: Option<SkillDependencies>,
    /// `description`.
    pub description: String,
    /// `enabled`.
    pub enabled: bool,
    /// `interface`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interface: Option<SkillInterface>,
    /// `name`.
    pub name: String,
    /// `path`.
    pub path: AbsolutePathBuf,
    /// `scope`.
    pub scope: SkillScope,
    /// Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub short_description: Option<String>,
}

/// `SkillsListEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillsListEntry {
    /// `cwd`.
    pub cwd: String,
    /// `errors`.
    pub errors: Vec<SkillErrorInfo>,
    /// `skills`.
    pub skills: Vec<SkillMetadata>,
}

/// `SkillsListResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillsListResponse {
    /// `data`.
    pub data: Vec<SkillsListEntry>,
}

/// `GetAccountParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetAccountParams {
    /// When `true`, requests a proactive token refresh before returning.
    ///
    /// In managed auth mode this triggers the normal refresh-token flow. In external auth mode this flag is ignored. Clients should refresh tokens themselves and call `account/login/start` with `chatgptAuthTokens`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<bool>,
}

/// `PlanType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PlanType {
    #[serde(rename = "free")]
    Free,
    #[serde(rename = "go")]
    Go,
    #[serde(rename = "plus")]
    Plus,
    #[serde(rename = "pro")]
    Pro,
    #[serde(rename = "prolite")]
    Prolite,
    #[serde(rename = "team")]
    Team,
    #[serde(rename = "self_serve_business_prolite")]
    SelfServeBusinessProlite,
    #[serde(rename = "self_serve_business_usage_based")]
    SelfServeBusinessUsageBased,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "ent26")]
    Ent26,
    #[serde(rename = "enterprise_cbp_automation")]
    EnterpriseCbpAutomation,
    #[serde(rename = "enterprise_cbp_usage_based")]
    EnterpriseCbpUsageBased,
    #[serde(rename = "enterprise")]
    Enterprise,
    #[serde(rename = "edu")]
    Edu,
    #[serde(rename = "unknown")]
    Unknown,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unrecognized,
}

/// `Account`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum Account {
    #[serde(rename = "apiKey")]
    ApiKey,
    #[serde(rename = "chatgpt")]
    Chatgpt {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        email: Option<String>,
        plan_type: PlanType,
    },
    #[serde(rename = "amazonBedrock")]
    AmazonBedrock {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        uses_codex_managed_credentials: Option<bool>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `GetAccountResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetAccountResponse {
    /// `account`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub account: Option<Account>,
    /// `requiresOpenaiAuth`.
    pub requires_openai_auth: bool,
}

/// `ModelRerouteReason`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ModelRerouteReason {
    #[serde(rename = "highRiskCyberActivity")]
    HighRiskCyberActivity,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `ModelReroutedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelReroutedNotification {
    /// `fromModel`.
    pub from_model: String,
    /// `reason`.
    pub reason: ModelRerouteReason,
    /// `threadId`.
    pub thread_id: String,
    /// `toModel`.
    pub to_model: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ModelSafetyBufferingUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelSafetyBufferingUpdatedNotification {
    /// `fasterModel`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub faster_model: Option<String>,
    /// `model`.
    pub model: String,
    /// `reasons`.
    pub reasons: Vec<String>,
    /// `showBufferingUi`.
    pub show_buffering_ui: bool,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
    /// `useCases`.
    pub use_cases: Vec<String>,
}

/// Authentication mode for OpenAI-backed providers.
pub type AuthMode = crate::agents::codex::tolerant::Tolerant<AuthModeKnown>;

/// The variants of `AuthMode` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AuthModeKnown {
    /// OpenAI API key provided by the caller and stored by Codex.
    #[serde(rename = "apikey")]
    Apikey,
    /// ChatGPT OAuth managed by Codex (tokens persisted and refreshed by Codex).
    #[serde(rename = "chatgpt")]
    Chatgpt,
    /// [UNSTABLE] FOR OPENAI INTERNAL USE ONLY - DO NOT USE.
    ///
    /// ChatGPT auth tokens are supplied by an external host app and are only stored in memory. Token refresh must be handled by the external host app.
    #[serde(rename = "chatgptAuthTokens")]
    ChatgptAuthTokens,
    /// Backend auth supplied as request headers.
    #[serde(rename = "headers")]
    Headers,
    /// Programmatic Codex auth backed by a registered Agent Identity.
    #[serde(rename = "agentIdentity")]
    AgentIdentity,
    /// Programmatic Codex auth backed by a personal access token.
    #[serde(rename = "personalAccessToken")]
    PersonalAccessToken,
    /// Amazon Bedrock bearer token managed by Codex.
    #[serde(rename = "bedrockApiKey")]
    BedrockApiKey,
}

/// `AccountUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccountUpdatedNotification {
    /// `authMode`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth_mode: Option<AuthMode>,
    /// `planType`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_type: Option<PlanType>,
}

/// `CreditsSnapshot`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreditsSnapshot {
    /// `balance`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub balance: Option<String>,
    /// `hasCredits`.
    pub has_credits: bool,
    /// `unlimited`.
    pub unlimited: bool,
}

/// `SpendControlLimitSnapshot`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SpendControlLimitSnapshot {
    /// `limit`.
    pub limit: String,
    /// `remainingPercent`.
    pub remaining_percent: i64,
    /// `resetsAt`.
    pub resets_at: i64,
    /// `used`.
    pub used: String,
}

/// `RateLimitWindow`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RateLimitWindow {
    /// `resetsAt`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resets_at: Option<i64>,
    /// `usedPercent`.
    pub used_percent: i64,
    /// `windowDurationMins`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window_duration_mins: Option<i64>,
}

/// `RateLimitReachedType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RateLimitReachedType {
    #[serde(rename = "rate_limit_reached")]
    RateLimitReached,
    #[serde(rename = "workspace_owner_credits_depleted")]
    WorkspaceOwnerCreditsDepleted,
    #[serde(rename = "workspace_member_credits_depleted")]
    WorkspaceMemberCreditsDepleted,
    #[serde(rename = "workspace_owner_usage_limit_reached")]
    WorkspaceOwnerUsageLimitReached,
    #[serde(rename = "workspace_member_usage_limit_reached")]
    WorkspaceMemberUsageLimitReached,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `RateLimitSnapshot`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RateLimitSnapshot {
    /// `credits`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credits: Option<CreditsSnapshot>,
    /// `individualLimit`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub individual_limit: Option<SpendControlLimitSnapshot>,
    /// `limitId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit_id: Option<String>,
    /// `limitName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit_name: Option<String>,
    /// `planType`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_type: Option<PlanType>,
    /// `primary`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub primary: Option<RateLimitWindow>,
    /// `rateLimitReachedType`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate_limit_reached_type: Option<RateLimitReachedType>,
    /// `secondary`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub secondary: Option<RateLimitWindow>,
    /// Backend-reported spend-control state. `None` is unavailable, not a sparse-update recovery.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spend_control_reached: Option<bool>,
}

/// Sparse rolling rate-limit update.
///
/// Clients should merge available values into the most recent `account/rateLimits/read` response or refetch that snapshot. Nullable account metadata may be unavailable in a rolling update and does not clear a previously observed value.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccountRateLimitsUpdatedNotification {
    /// `rateLimits`.
    pub rate_limits: RateLimitSnapshot,
}
