// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the approvals methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `AdditionalPermissionProfile`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdditionalPermissionProfile {
    /// `fileSystem`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_system: Option<AdditionalFileSystemPermissions>,
    /// Partial overlay used for per-command permission requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<AdditionalNetworkPermissions>,
}

/// `CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendmentAcceptWithExecpolicyAmendment`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendmentAcceptWithExecpolicyAmendment
{
    /// `execpolicy_amendment`.
    #[serde(rename = "execpolicy_amendment")]
    pub execpolicy_amendment: Vec<String>,
}

/// `NetworkPolicyRuleAction`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkPolicyRuleAction {
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "deny")]
    Deny,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `NetworkPolicyAmendment`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NetworkPolicyAmendment {
    /// `action`.
    pub action: NetworkPolicyRuleAction,
    /// `host`.
    pub host: String,
}

/// `CommandExecutionApprovalDecisionApplyNetworkPolicyAmendmentApplyNetworkPolicyAmendment`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandExecutionApprovalDecisionApplyNetworkPolicyAmendmentApplyNetworkPolicyAmendment {
    /// `network_policy_amendment`.
    #[serde(rename = "network_policy_amendment")]
    pub network_policy_amendment: NetworkPolicyAmendment,
}

/// `CommandExecutionApprovalDecision`.
pub type CommandExecutionApprovalDecision =
    crate::agents::codex::tolerant::Tolerant<CommandExecutionApprovalDecisionKnown>;

/// The variants of `CommandExecutionApprovalDecision` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CommandExecutionApprovalDecisionKnown {
    /// User approved the command.
    #[serde(rename = "accept")]
    Accept,
    /// User approved the command and future prompts in the same session-scoped approval cache should run without prompting.
    #[serde(rename = "acceptForSession")]
    AcceptForSession,
    /// User approved the command, and wants to apply the proposed execpolicy amendment so future matching commands can run without prompting.
    #[serde(rename = "acceptWithExecpolicyAmendment")]
    AcceptWithExecpolicyAmendment(
        CommandExecutionApprovalDecisionAcceptWithExecpolicyAmendmentAcceptWithExecpolicyAmendment,
    ),
    /// User chose a persistent network policy rule (allow/deny) for this host.
    #[serde(rename = "applyNetworkPolicyAmendment")]
    ApplyNetworkPolicyAmendment(
        CommandExecutionApprovalDecisionApplyNetworkPolicyAmendmentApplyNetworkPolicyAmendment,
    ),
    /// User denied the command. The agent will continue the turn.
    #[serde(rename = "decline")]
    Decline,
    /// User denied the command. The turn will also be immediately interrupted.
    #[serde(rename = "cancel")]
    Cancel,
}

/// `NetworkApprovalContext`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NetworkApprovalContext {
    /// `host`.
    pub host: String,
    /// `protocol`.
    pub protocol: NetworkApprovalProtocol,
}

/// `CommandExecutionRequestApprovalParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandExecutionRequestApprovalParams {
    /// Optional additional permissions requested for this command.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_permissions: Option<AdditionalPermissionProfile>,
    /// Unique identifier for this specific approval callback.
    ///
    /// For regular shell/unified_exec approvals, this is null.
    ///
    /// For zsh-exec-bridge subcommand approvals, multiple callbacks can belong to one parent `itemId`, so `approvalId` is a distinct opaque callback id (a UUID) used to disambiguate routing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<String>,
    /// Ordered list of decisions the client may present for this prompt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available_decisions: Option<Vec<CommandExecutionApprovalDecision>>,
    /// The command to be executed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// Best-effort parsed command actions for friendly display.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command_actions: Option<Vec<CommandAction>>,
    /// The command's working directory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<LegacyAppPathString>,
    /// Environment in which the command will run.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment_id: Option<String>,
    /// `itemId`.
    pub item_id: String,
    /// Optional context for a managed-network approval prompt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network_approval_context: Option<NetworkApprovalContext>,
    /// Optional proposed execpolicy amendment to allow similar commands without prompting.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proposed_execpolicy_amendment: Option<Vec<String>>,
    /// Optional proposed network policy amendments (allow/deny host) for future requests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub proposed_network_policy_amendments: Option<Vec<NetworkPolicyAmendment>>,
    /// Optional explanatory reason (e.g. request for network access).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Unix timestamp (in milliseconds) when this approval request started.
    pub started_at_ms: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `CommandExecutionRequestApprovalResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandExecutionRequestApprovalResponse {
    /// `decision`.
    pub decision: CommandExecutionApprovalDecision,
}

/// `FileChangeRequestApprovalParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileChangeRequestApprovalParams {
    /// [UNSTABLE] When set, the agent is asking the user to allow writes under this root for the remainder of the session (unclear if this is honored today).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grant_root: Option<String>,
    /// `itemId`.
    pub item_id: String,
    /// Optional explanatory reason (e.g. request for extra write access).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Unix timestamp (in milliseconds) when this approval request started.
    pub started_at_ms: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `FileChangeApprovalDecision`.
pub type FileChangeApprovalDecision =
    crate::agents::codex::tolerant::Tolerant<FileChangeApprovalDecisionKnown>;

/// The variants of `FileChangeApprovalDecision` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum FileChangeApprovalDecisionKnown {
    /// User approved the file changes.
    #[serde(rename = "accept")]
    Accept,
    /// User approved the file changes and future changes to the same files should run without prompting.
    #[serde(rename = "acceptForSession")]
    AcceptForSession,
    /// User denied the file changes. The agent will continue the turn.
    #[serde(rename = "decline")]
    Decline,
    /// User denied the file changes. The turn will also be immediately interrupted.
    #[serde(rename = "cancel")]
    Cancel,
}

/// `FileChangeRequestApprovalResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileChangeRequestApprovalResponse {
    /// `decision`.
    pub decision: FileChangeApprovalDecision,
}

/// EXPERIMENTAL. Defines a single selectable option for request_user_input.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputOption {
    /// `description`.
    pub description: String,
    /// `label`.
    pub label: String,
}

/// EXPERIMENTAL. Represents one request_user_input question and its required options.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputQuestion {
    /// `header`.
    pub header: String,
    /// `id`.
    pub id: String,
    /// `isOther`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_other: Option<bool>,
    /// `isSecret`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_secret: Option<bool>,
    /// `options`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<ToolRequestUserInputOption>>,
    /// `question`.
    pub question: String,
}

/// EXPERIMENTAL. Params sent with a request_user_input event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputParams {
    /// @deprecated Use `isBlocking` to decide whether the request should block.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auto_resolution_ms: Option<u64>,
    /// `isBlocking`.
    pub is_blocking: bool,
    /// `itemId`.
    pub item_id: String,
    /// `questions`.
    pub questions: Vec<ToolRequestUserInputQuestion>,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// EXPERIMENTAL. Response payload mapping question ids to answers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolRequestUserInputResponse {
    /// `answers`.
    pub answers: serde_json::Value,
}

/// `PermissionsRequestApprovalParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PermissionsRequestApprovalParams {
    /// `cwd`.
    pub cwd: AbsolutePathBuf,
    /// `environmentId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment_id: Option<String>,
    /// `itemId`.
    pub item_id: String,
    /// `permissions`.
    pub permissions: RequestPermissionProfile,
    /// `reason`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Unix timestamp (in milliseconds) when this approval request started.
    pub started_at_ms: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `GrantedPermissionProfile`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GrantedPermissionProfile {
    /// `fileSystem`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_system: Option<AdditionalFileSystemPermissions>,
    /// `network`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<AdditionalNetworkPermissions>,
}

/// `PermissionGrantScope`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PermissionGrantScope {
    #[serde(rename = "turn")]
    Turn,
    #[serde(rename = "session")]
    Session,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `PermissionsRequestApprovalResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PermissionsRequestApprovalResponse {
    /// `permissions`.
    pub permissions: GrantedPermissionProfile,
    /// `scope`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<PermissionGrantScope>,
    /// Review every subsequent command in this turn before normal sandboxed execution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strict_auto_review: Option<bool>,
}

/// `McpElicitationObjectType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum McpElicitationObjectType {
    #[serde(rename = "object")]
    Object,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// Typed form schema for MCP `elicitation/create` requests.
///
/// This matches the `requestedSchema` shape from the MCP 2025-11-25 `ElicitRequestFormParams` schema.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpElicitationSchema {
    /// `$schema`.
    #[serde(rename = "$schema", default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    /// `properties`.
    pub properties: serde_json::Value,
    /// `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub required: Option<Vec<String>>,
    /// `type`.
    pub r#type: McpElicitationObjectType,
}

/// `McpServerElicitationRequestParamsVariant`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "mode",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum McpServerElicitationRequestParamsVariant {
    #[serde(rename = "form")]
    Form {
        #[serde(rename = "_meta", default, skip_serializing_if = "Option::is_none")]
        meta: Option<serde_json::Value>,
        message: String,
        requested_schema: McpElicitationSchema,
    },
    #[serde(rename = "openai/form")]
    OpenaiForm {
        #[serde(rename = "_meta", default, skip_serializing_if = "Option::is_none")]
        meta: Option<serde_json::Value>,
        message: String,
        requested_schema: serde_json::Value,
    },
    #[serde(rename = "url")]
    Url {
        #[serde(rename = "_meta", default, skip_serializing_if = "Option::is_none")]
        meta: Option<serde_json::Value>,
        elicitation_id: String,
        message: String,
        url: String,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `McpServerElicitationRequestParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerElicitationRequestParams {
    /// `serverName`.
    pub server_name: String,
    /// `threadId`.
    pub thread_id: String,
    /// Active Codex turn when this elicitation was observed, if app-server could correlate one.
    ///
    /// This is nullable because MCP models elicitation as a standalone server-to-client request identified by the MCP server request id. It may be triggered during a turn, but turn context is app-server correlation rather than part of the protocol identity of the elicitation itself.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
    /// The variant the schema flattens into this object.
    #[serde(flatten)]
    pub variant: McpServerElicitationRequestParamsVariant,
}

/// `McpServerElicitationAction`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum McpServerElicitationAction {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "decline")]
    Decline,
    #[serde(rename = "cancel")]
    Cancel,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `McpServerElicitationRequestResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerElicitationRequestResponse {
    /// Optional client metadata for form-mode action handling.
    #[serde(rename = "_meta", default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    /// `action`.
    pub action: McpServerElicitationAction,
    /// Structured user input for accepted elicitations, mirroring RMCP `CreateElicitationResult`.
    ///
    /// This is nullable because decline/cancel responses have no content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<serde_json::Value>,
}

/// `RequestId`.
pub type RequestId = serde_json::Value;

/// `ServerRequestResolvedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerRequestResolvedNotification {
    /// `requestId`.
    pub request_id: RequestId,
    /// `threadId`.
    pub thread_id: String,
}
