// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the common methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `WarningNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WarningNotification {
    /// Concise warning message for the user.
    pub message: String,
    /// Optional thread target when the warning applies to a specific thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

/// `GuardianWarningNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuardianWarningNotification {
    /// Concise guardian warning message for the user.
    pub message: String,
    /// Thread target for the guardian warning.
    pub thread_id: String,
}

/// `DeprecationNoticeNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeprecationNoticeNotification {
    /// Optional extra guidance, such as migration steps or rationale.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// Concise summary of what is deprecated.
    pub summary: String,
}

/// `TextPosition`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TextPosition {
    /// 1-based column number (in Unicode scalar values).
    pub column: u64,
    /// 1-based line number.
    pub line: u64,
}

/// `TextRange`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TextRange {
    /// `end`.
    pub end: TextPosition,
    /// `start`.
    pub start: TextPosition,
}

/// `ConfigWarningNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConfigWarningNotification {
    /// Optional extra guidance or error details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// Optional path to the config file that triggered the warning.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Optional range for the error location inside the config file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub range: Option<TextRange>,
    /// Concise summary of the warning.
    pub summary: String,
}

/// `McpServerStartupFailureReason`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum McpServerStartupFailureReason {
    #[serde(rename = "reauthenticationRequired")]
    ReauthenticationRequired,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `McpServerStartupState`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum McpServerStartupState {
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `McpServerStatusUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerStatusUpdatedNotification {
    /// `error`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// `failureReason`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<McpServerStartupFailureReason>,
    /// `name`.
    pub name: String,
    /// `status`.
    pub status: McpServerStartupState,
    /// `threadId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

/// `McpServerOauthLoginCompletedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpServerOauthLoginCompletedNotification {
    /// `error`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// `name`.
    pub name: String,
    /// `success`.
    pub success: bool,
    /// `threadId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

/// `HookOutputEntryKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookOutputEntryKind {
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "feedback")]
    Feedback,
    #[serde(rename = "context")]
    Context,
    #[serde(rename = "error")]
    Error,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookOutputEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HookOutputEntry {
    /// `kind`.
    pub kind: HookOutputEntryKind,
    /// `text`.
    pub text: String,
}

/// `HookEventName`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookEventName {
    #[serde(rename = "preToolUse")]
    PreToolUse,
    #[serde(rename = "permissionRequest")]
    PermissionRequest,
    #[serde(rename = "postToolUse")]
    PostToolUse,
    #[serde(rename = "preCompact")]
    PreCompact,
    #[serde(rename = "postCompact")]
    PostCompact,
    #[serde(rename = "sessionStart")]
    SessionStart,
    #[serde(rename = "sessionEnd")]
    SessionEnd,
    #[serde(rename = "userPromptSubmit")]
    UserPromptSubmit,
    #[serde(rename = "subagentStart")]
    SubagentStart,
    #[serde(rename = "subagentStop")]
    SubagentStop,
    #[serde(rename = "stop")]
    Stop,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookExecutionMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookExecutionMode {
    #[serde(rename = "sync")]
    Sync,
    #[serde(rename = "async")]
    Async,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookHandlerType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookHandlerType {
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "prompt")]
    Prompt,
    #[serde(rename = "agent")]
    Agent,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookScope`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookScope {
    #[serde(rename = "thread")]
    Thread,
    #[serde(rename = "turn")]
    Turn,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookSource {
    #[serde(rename = "system")]
    System,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "project")]
    Project,
    #[serde(rename = "mdm")]
    Mdm,
    #[serde(rename = "sessionFlags")]
    SessionFlags,
    #[serde(rename = "plugin")]
    Plugin,
    #[serde(rename = "cloudRequirements")]
    CloudRequirements,
    #[serde(rename = "cloudManagedConfig")]
    CloudManagedConfig,
    #[serde(rename = "legacyManagedConfigFile")]
    LegacyManagedConfigFile,
    #[serde(rename = "legacyManagedConfigMdm")]
    LegacyManagedConfigMdm,
    #[serde(rename = "unknown")]
    Unknown,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unrecognized,
}

/// `HookRunStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum HookRunStatus {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "stopped")]
    Stopped,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `HookRunSummary`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HookRunSummary {
    /// `completedAt`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<i64>,
    /// `displayOrder`.
    pub display_order: i64,
    /// `durationMs`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    /// `entries`.
    pub entries: Vec<HookOutputEntry>,
    /// `eventName`.
    pub event_name: HookEventName,
    /// `executionMode`.
    pub execution_mode: HookExecutionMode,
    /// `handlerType`.
    pub handler_type: HookHandlerType,
    /// `id`.
    pub id: String,
    /// `scope`.
    pub scope: HookScope,
    /// `source`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<HookSource>,
    /// `sourcePath`.
    pub source_path: AbsolutePathBuf,
    /// `startedAt`.
    pub started_at: i64,
    /// `status`.
    pub status: HookRunStatus,
    /// `statusMessage`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_message: Option<String>,
}

/// `HookStartedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HookStartedNotification {
    /// `run`.
    pub run: HookRunSummary,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}

/// `HookCompletedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HookCompletedNotification {
    /// `run`.
    pub run: HookRunSummary,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}
