// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the handshake methods.

use serde::{Deserialize, Serialize};

/// Client-declared capabilities negotiated during initialize.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitializeCapabilities {
    /// Opt into receiving experimental API methods and fields.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub experimental_api: Option<bool>,
    /// MCP extension settings declared by the app-server client.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extensions: Option<serde_json::Value>,
    /// Legacy opt-in for the `openai/form` MCP extension.
    ///
    /// New clients should declare `openai/form` in [`Self::extensions`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mcp_server_openai_form_elicitation: Option<bool>,
    /// Exact notification method names that should be suppressed for this connection (for example `thread/started`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opt_out_notification_methods: Option<Vec<String>>,
    /// Opt into `attestation/generate` requests for upstream `x-oai-attestation`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_attestation: Option<bool>,
}

/// `ClientInfo`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientInfo {
    /// `name`.
    pub name: String,
    /// `title`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// `version`.
    pub version: String,
}

/// `InitializeParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitializeParams {
    /// `capabilities`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capabilities: Option<InitializeCapabilities>,
    /// `clientInfo`.
    pub client_info: ClientInfo,
}

pub type AbsolutePathBuf = String;

/// `InitializeResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InitializeResponse {
    /// Absolute path to the server's $CODEX_HOME directory.
    pub codex_home: AbsolutePathBuf,
    /// Platform family for the running app-server target, for example `"unix"` or `"windows"`.
    pub platform_family: String,
    /// Operating system for the running app-server target, for example `"macos"`, `"linux"`, or `"windows"`.
    pub platform_os: String,
    /// `userAgent`.
    pub user_agent: String,
}
