// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the items methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `ItemStartedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemStartedNotification {
    /// `item`.
    pub item: ThreadItem,
    /// Unix timestamp (in milliseconds) when this item lifecycle started.
    pub started_at_ms: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ItemCompletedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemCompletedNotification {
    /// Unix timestamp (in milliseconds) when this item lifecycle completed.
    pub completed_at_ms: i64,
    /// `item`.
    pub item: ThreadItem,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `AgentMessageDeltaNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentMessageDeltaNotification {
    /// `delta`.
    pub delta: String,
    /// `itemId`.
    pub item_id: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ReasoningSummaryTextDeltaNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasoningSummaryTextDeltaNotification {
    /// `delta`.
    pub delta: String,
    /// `itemId`.
    pub item_id: String,
    /// `summaryIndex`.
    pub summary_index: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ReasoningSummaryPartAddedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasoningSummaryPartAddedNotification {
    /// `itemId`.
    pub item_id: String,
    /// `summaryIndex`.
    pub summary_index: i64,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ReasoningTextDeltaNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasoningTextDeltaNotification {
    /// `contentIndex`.
    pub content_index: i64,
    /// `delta`.
    pub delta: String,
    /// `itemId`.
    pub item_id: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// EXPERIMENTAL - proposed plan streaming deltas for plan items. Clients should not assume concatenated deltas match the completed plan item content.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanDeltaNotification {
    /// `delta`.
    pub delta: String,
    /// `itemId`.
    pub item_id: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `CommandExecutionOutputDeltaNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandExecutionOutputDeltaNotification {
    /// `delta`.
    pub delta: String,
    /// `itemId`.
    pub item_id: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `TerminalInteractionNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TerminalInteractionNotification {
    /// `itemId`.
    pub item_id: String,
    /// `processId`.
    pub process_id: String,
    /// `stdin`.
    pub stdin: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `FileChangePatchUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileChangePatchUpdatedNotification {
    /// `changes`.
    pub changes: Vec<FileUpdateChange>,
    /// `itemId`.
    pub item_id: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `McpToolCallProgressNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolCallProgressNotification {
    /// `itemId`.
    pub item_id: String,
    /// `message`.
    pub message: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `GuardianCommandSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GuardianCommandSource {
    #[serde(rename = "shell")]
    Shell,
    #[serde(rename = "unifiedExec")]
    UnifiedExec,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `NetworkApprovalProtocol`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkApprovalProtocol {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "https")]
    Https,
    #[serde(rename = "socks5Tcp")]
    Socks5Tcp,
    #[serde(rename = "socks5Udp")]
    Socks5Udp,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `FileSystemAccessMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FileSystemAccessMode {
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "deny")]
    Deny,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `FileSystemSpecialPath`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum FileSystemSpecialPath {
    #[serde(rename = "root")]
    Root,
    #[serde(rename = "minimal")]
    Minimal,
    #[serde(rename = "project_roots")]
    ProjectRoots {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        subpath: Option<LegacyAppPathString>,
    },
    #[serde(rename = "tmpdir")]
    Tmpdir,
    #[serde(rename = "slash_tmp")]
    SlashTmp,
    #[serde(rename = "unknown")]
    Unknown {
        path: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        subpath: Option<LegacyAppPathString>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unrecognized,
}

/// `FileSystemPath`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum FileSystemPath {
    #[serde(rename = "path")]
    Path { path: LegacyAppPathString },
    #[serde(rename = "glob_pattern")]
    GlobPattern { pattern: String },
    #[serde(rename = "special")]
    Special { value: FileSystemSpecialPath },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `FileSystemSandboxEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileSystemSandboxEntry {
    /// `access`.
    pub access: FileSystemAccessMode,
    /// `path`.
    pub path: FileSystemPath,
}

/// `AdditionalFileSystemPermissions`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdditionalFileSystemPermissions {
    /// `entries`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<FileSystemSandboxEntry>>,
    /// `globScanMaxDepth`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glob_scan_max_depth: Option<u64>,
    /// This will be removed in favor of `entries`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub read: Option<Vec<LegacyAppPathString>>,
    /// This will be removed in favor of `entries`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub write: Option<Vec<LegacyAppPathString>>,
}

/// `AdditionalNetworkPermissions`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdditionalNetworkPermissions {
    /// `enabled`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

/// `RequestPermissionProfile`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestPermissionProfile {
    /// `fileSystem`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub file_system: Option<AdditionalFileSystemPermissions>,
    /// `network`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub network: Option<AdditionalNetworkPermissions>,
}

/// `GuardianApprovalReviewAction`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum GuardianApprovalReviewAction {
    #[serde(rename = "command")]
    Command {
        command: String,
        cwd: AbsolutePathBuf,
        source: GuardianCommandSource,
    },
    #[serde(rename = "execve")]
    Execve {
        argv: Vec<String>,
        cwd: AbsolutePathBuf,
        program: String,
        source: GuardianCommandSource,
    },
    #[serde(rename = "applyPatch")]
    ApplyPatch {
        cwd: AbsolutePathBuf,
        files: Vec<AbsolutePathBuf>,
    },
    #[serde(rename = "networkAccess")]
    NetworkAccess {
        host: String,
        port: u64,
        protocol: NetworkApprovalProtocol,
        target: String,
    },
    #[serde(rename = "mcpToolCall")]
    McpToolCall {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        connector_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        connector_name: Option<String>,
        server: String,
        tool_name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        tool_title: Option<String>,
    },
    #[serde(rename = "requestPermissions")]
    RequestPermissions {
        permissions: RequestPermissionProfile,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// [UNSTABLE] Risk level assigned by approval auto-review.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GuardianRiskLevel {
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "critical")]
    Critical,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// [UNSTABLE] Lifecycle state for an approval auto-review.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GuardianApprovalReviewStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "timedOut")]
    TimedOut,
    #[serde(rename = "aborted")]
    Aborted,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// [UNSTABLE] Authorization level assigned by approval auto-review.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GuardianUserAuthorization {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "high")]
    High,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unrecognized,
}

/// [UNSTABLE] Temporary approval auto-review payload used by `item/autoApprovalReview/*` notifications. This shape is expected to change soon.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GuardianApprovalReview {
    /// `rationale`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,
    /// `riskLevel`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub risk_level: Option<GuardianRiskLevel>,
    /// `status`.
    pub status: GuardianApprovalReviewStatus,
    /// `userAuthorization`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_authorization: Option<GuardianUserAuthorization>,
}

/// [UNSTABLE] Temporary notification payload for approval auto-review. This shape is expected to change soon.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemGuardianApprovalReviewStartedNotification {
    /// `action`.
    pub action: GuardianApprovalReviewAction,
    /// `review`.
    pub review: GuardianApprovalReview,
    /// Stable identifier for this review.
    pub review_id: String,
    /// Unix timestamp (in milliseconds) when this review started.
    pub started_at_ms: i64,
    /// Identifier for the reviewed item or tool call when one exists.
    ///
    /// In most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item
    ///
    /// A network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_item_id: Option<String>,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// [UNSTABLE] Source that produced a terminal approval auto-review decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AutoReviewDecisionSource {
    #[serde(rename = "agent")]
    Agent,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// [UNSTABLE] Temporary notification payload for approval auto-review. This shape is expected to change soon.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemGuardianApprovalReviewCompletedNotification {
    /// `action`.
    pub action: GuardianApprovalReviewAction,
    /// Unix timestamp (in milliseconds) when this review completed.
    pub completed_at_ms: i64,
    /// `decisionSource`.
    pub decision_source: AutoReviewDecisionSource,
    /// `review`.
    pub review: GuardianApprovalReview,
    /// Stable identifier for this review.
    pub review_id: String,
    /// Unix timestamp (in milliseconds) when this review started.
    pub started_at_ms: i64,
    /// Identifier for the reviewed item or tool call when one exists.
    ///
    /// In most cases, one review maps to one target item. The exceptions are - execve reviews, where a single command may contain multiple execve calls to review (only possible when using the shell_zsh_fork feature) - network policy reviews, where there is no target item
    ///
    /// A network call is triggered by a CommandExecution item, so having a target_item_id set to the CommandExecution item would be misleading because the review is about the network call, not the command execution. Therefore, target_item_id is set to None for network policy reviews.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_item_id: Option<String>,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}
