// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the threads methods, part 4.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// There are two ways to fork a thread: 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread. 2. By path: load the thread from disk by path and fork it into a new thread.
///
/// If using a non-empty path, the thread_id param will be ignored. Empty string path values are treated as absent.
///
/// Prefer using thread_id whenever possible.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadForkParams {
    /// `approvalPolicy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<AskForApproval>,
    /// Override where approval requests are routed for review on this thread and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvals_reviewer: Option<ApprovalsReviewer>,
    /// `baseInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_instructions: Option<String>,
    /// Optional turn id to fork before, excluding that turn and all later turns. Cannot be combined with `last_turn_id`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub before_turn_id: Option<String>,
    /// `config`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// `cwd`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// When true, carry the source thread's current goal into the fork without starting its initial automatic continuation. The next explicit turn owns the goal lifecycle, and normal automatic continuation resumes after it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub defer_goal_continuation: Option<bool>,
    /// `developerInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub developer_instructions: Option<String>,
    /// `ephemeral`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    /// When true, return only thread metadata and live fork state without populating `thread.turns`. This is useful when the client plans to call `thread/turns/list` immediately after forking.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_turns: Option<bool>,
    /// Optional last turn id to fork through, inclusive.
    ///
    /// When specified, turns after `last_turn_id` are omitted from the fork. The referenced turn cannot be in progress.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_turn_id: Option<String>,
    /// Configuration overrides for the forked thread, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// `modelProvider`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_provider: Option<String>,
    /// [UNSTABLE] Specify the rollout path to fork from. If specified, the thread_id param will be ignored.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Named profile id for the forked thread. Cannot be combined with `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// Replace the thread's runtime workspace roots. Paths must be absolute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<SandboxMode>,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `threadId`.
    pub thread_id: String,
    /// Optional client-supplied analytics source classification for this forked thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_source: Option<ThreadSource>,
}

/// `ThreadForkResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadForkResponse {
    /// Named or implicit built-in profile that produced the active permissions, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_permission_profile: Option<ActivePermissionProfile>,
    /// `approvalPolicy`.
    pub approval_policy: AskForApproval,
    /// Reviewer currently used for approval requests on this thread.
    pub approvals_reviewer: ApprovalsReviewer,
    /// `cwd`.
    pub cwd: AbsolutePathBuf,
    /// Environment-native paths to instruction source files currently loaded for this thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instruction_sources: Option<Vec<LegacyAppPathString>>,
    /// `model`.
    pub model: String,
    /// `modelProvider`.
    pub model_provider: String,
    /// @deprecated Always `explicitRequestOnly`. Use `reasoningEffort` for Ultra behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// `reasoningEffort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Thread-scoped runtime workspace roots used to materialize `:workspace_roots`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.
    pub sandbox: SandboxPolicy,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `thread`.
    pub thread: Thread,
}

/// `ThreadUnsubscribeParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadUnsubscribeParams {
    /// `threadId`.
    pub thread_id: String,
}

/// `ThreadUnsubscribeStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadUnsubscribeStatus {
    #[serde(rename = "notLoaded")]
    NotLoaded,
    #[serde(rename = "notSubscribed")]
    NotSubscribed,
    #[serde(rename = "unsubscribed")]
    Unsubscribed,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `ThreadUnsubscribeResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadUnsubscribeResponse {
    /// `status`.
    pub status: ThreadUnsubscribeStatus,
}

/// `ThreadStartedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadStartedNotification {
    /// `thread`.
    pub thread: Thread,
}

/// `ThreadStatusChangedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadStatusChangedNotification {
    /// `status`.
    pub status: ThreadStatus,
    /// `threadId`.
    pub thread_id: String,
}

/// `ThreadSettings`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadSettings {
    /// `activePermissionProfile`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_permission_profile: Option<ActivePermissionProfile>,
    /// `approvalPolicy`.
    pub approval_policy: AskForApproval,
    /// `approvalsReviewer`.
    pub approvals_reviewer: ApprovalsReviewer,
    /// `collaborationMode`.
    pub collaboration_mode: CollaborationMode,
    /// `cwd`.
    pub cwd: AbsolutePathBuf,
    /// `effort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// `model`.
    pub model: String,
    /// `modelProvider`.
    pub model_provider: String,
    /// @deprecated Always `explicitRequestOnly`. Use `effort` for Ultra behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// `personality`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personality: Option<Personality>,
    /// `sandboxPolicy`.
    pub sandbox_policy: SandboxPolicy,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `summary`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<ReasoningSummary>,
}

/// `ThreadSettingsUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadSettingsUpdatedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `threadSettings`.
    pub thread_settings: ThreadSettings,
}

/// `TokenUsageBreakdown`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenUsageBreakdown {
    /// `cacheWriteInputTokens`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_write_input_tokens: Option<i64>,
    /// `cachedInputTokens`.
    pub cached_input_tokens: i64,
    /// `inputTokens`.
    pub input_tokens: i64,
    /// `outputTokens`.
    pub output_tokens: i64,
    /// `reasoningOutputTokens`.
    pub reasoning_output_tokens: i64,
    /// `totalTokens`.
    pub total_tokens: i64,
}

/// `ThreadTokenUsage`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadTokenUsage {
    /// `last`.
    pub last: TokenUsageBreakdown,
    /// `modelContextWindow`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_context_window: Option<i64>,
    /// `total`.
    pub total: TokenUsageBreakdown,
}

/// `ThreadTokenUsageUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadTokenUsageUpdatedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `tokenUsage`.
    pub token_usage: ThreadTokenUsage,
    /// `turnId`.
    pub turn_id: String,
}

/// `ThreadNameUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadNameUpdatedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `threadName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_name: Option<String>,
}

/// `ThreadClosedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadClosedNotification {
    /// `threadId`.
    pub thread_id: String,
}

/// `EnvironmentConnectionNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentConnectionNotification {
    /// `environmentId`.
    pub environment_id: String,
    /// `threadId`.
    pub thread_id: String,
}

/// Deprecated: Use `ContextCompaction` item type instead.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ContextCompactedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

pub type SkillsChangedNotification = serde_json::Value;
