// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the threads methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `AskForApprovalGranularGranular`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AskForApprovalGranularGranular {
    /// `mcp_elicitations`.
    #[serde(rename = "mcp_elicitations")]
    pub mcp_elicitations: bool,
    /// `request_permissions`.
    #[serde(
        rename = "request_permissions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub request_permissions: Option<bool>,
    /// `rules`.
    pub rules: bool,
    /// `sandbox_approval`.
    #[serde(rename = "sandbox_approval")]
    pub sandbox_approval: bool,
    /// `skill_approval`.
    #[serde(
        rename = "skill_approval",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub skill_approval: Option<bool>,
}

/// `AskForApproval`.
pub type AskForApproval = crate::agents::codex::tolerant::Tolerant<AskForApprovalKnown>;

/// The variants of `AskForApproval` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum AskForApprovalKnown {
    #[serde(rename = "untrusted")]
    Untrusted,
    #[serde(rename = "on-request")]
    OnRequest,
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "granular")]
    Granular(AskForApprovalGranularGranular),
}

/// Configures who approval requests are routed to for review. Examples include sandbox escapes, blocked network access, MCP approval prompts, and ARC escalations. Defaults to `user`. `auto_review` uses a carefully prompted subagent to gather relevant context and apply a risk-based decision framework before approving or denying the request. The legacy value `guardian_subagent` is accepted for compatibility.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalsReviewer {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "auto_review")]
    AutoReview,
    #[serde(rename = "guardian_subagent")]
    GuardianSubagent,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `FunctionDynamicToolNamespaceToolType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FunctionDynamicToolNamespaceToolType {
    #[serde(rename = "function")]
    Function,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `FunctionDynamicToolNamespaceTool`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionDynamicToolNamespaceTool {
    /// `deferLoading`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub defer_loading: Option<bool>,
    /// `description`.
    pub description: String,
    /// `inputSchema`.
    pub input_schema: serde_json::Value,
    /// `name`.
    pub name: String,
    /// `type`.
    pub r#type: FunctionDynamicToolNamespaceToolType,
}

pub type DynamicToolNamespaceTool = FunctionDynamicToolNamespaceTool;

/// `DynamicToolSpec`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum DynamicToolSpec {
    #[serde(rename = "function")]
    Function {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        defer_loading: Option<bool>,
        description: String,
        input_schema: serde_json::Value,
        name: String,
    },
    #[serde(rename = "namespace")]
    Namespace {
        description: String,
        name: String,
        tools: Vec<DynamicToolNamespaceTool>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

pub type LegacyAppPathString = String;

/// `TurnEnvironmentParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnEnvironmentParams {
    /// `cwd`.
    pub cwd: LegacyAppPathString,
    /// `environmentId`.
    pub environment_id: String,
    /// Environment-native runtime workspace roots. Omitted defaults to `cwd`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<LegacyAppPathString>>,
}

/// `ThreadHistoryMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadHistoryMode {
    #[serde(rename = "legacy")]
    Legacy,
    #[serde(rename = "paginated")]
    Paginated,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// Controls the effective multi-agent delegation instructions for a turn. `custom` means the configured mode hint defines the policy instead of a built-in policy.
pub type MultiAgentMode = crate::agents::codex::tolerant::Tolerant<MultiAgentModeKnown>;

/// The variants of `MultiAgentMode` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum MultiAgentModeKnown {
    #[serde(rename = "explicitRequestOnly")]
    ExplicitRequestOnly,
    #[serde(rename = "proactive")]
    Proactive,
    #[serde(rename = "custom")]
    Custom(String),
}

/// `Personality`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Personality {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "friendly")]
    Friendly,
    #[serde(rename = "pragmatic")]
    Pragmatic,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `SandboxMode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SandboxMode {
    #[serde(rename = "read-only")]
    ReadOnly,
    #[serde(rename = "workspace-write")]
    WorkspaceWrite,
    #[serde(rename = "danger-full-access")]
    DangerFullAccess,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `EnvironmentCapabilityRootLocationType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EnvironmentCapabilityRootLocationType {
    #[serde(rename = "environment")]
    Environment,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// A path owned by an execution environment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EnvironmentCapabilityRootLocation {
    /// `environmentId`.
    pub environment_id: String,
    /// Absolute path for the root in the selected environment.
    pub path: String,
    /// `type`.
    pub r#type: EnvironmentCapabilityRootLocationType,
}

pub type CapabilityRootLocation = EnvironmentCapabilityRootLocation;

/// A user-selected root that can expose one or more runtime capabilities.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SelectedCapabilityRoot {
    /// Stable identifier supplied by the capability selection platform.
    pub id: String,
    /// Where the selected root can be resolved.
    pub location: CapabilityRootLocation,
}

/// `ThreadStartSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadStartSource {
    #[serde(rename = "startup")]
    Startup,
    #[serde(rename = "clear")]
    Clear,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

pub type ThreadSource = String;

/// `ThreadStartParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadStartParams {
    /// Allow a provider with an authoritative static model catalog to replace an unavailable requested model with its default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_provider_model_fallback: Option<bool>,
    /// `approvalPolicy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<AskForApproval>,
    /// Override where approval requests are routed for review on this thread and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvals_reviewer: Option<ApprovalsReviewer>,
    /// `baseInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_instructions: Option<String>,
    /// `config`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// `cwd`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// `developerInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub developer_instructions: Option<String>,
    /// `dynamicTools`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dynamic_tools: Option<Vec<DynamicToolSpec>>,
    /// Optional sticky environments for this thread.
    ///
    /// Omitted selects the default environment when environment access is enabled. Empty disables environment access for turns that do not provide a turn override. Non-empty selects the first environment as the current turn environment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<TurnEnvironmentParams>>,
    /// `ephemeral`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    /// If true, opt into emitting raw Responses API items on the event stream. This is for internal use only (e.g. Codex Cloud).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub experimental_raw_events: Option<bool>,
    /// Persisted thread history contract to use for this new thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history_mode: Option<ThreadHistoryMode>,
    /// Test-only experimental field used to validate experimental gating and schema filtering behavior in a stable way.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mock_experimental_field: Option<String>,
    /// `model`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// `modelProvider`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_provider: Option<String>,
    /// @deprecated Ignored. Use Ultra reasoning effort for proactive multi-agent behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// Named profile id for this thread. Cannot be combined with `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// `personality`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personality: Option<Personality>,
    /// Replace the thread's runtime workspace roots. Paths must be absolute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<SandboxMode>,
    /// Capability roots selected for this thread by the hosting platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selected_capability_roots: Option<Vec<SelectedCapabilityRoot>>,
    /// `serviceName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `sessionStartSource`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_start_source: Option<ThreadStartSource>,
    /// Optional client-supplied analytics source classification for this thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_source: Option<ThreadSource>,
}

/// `ActivePermissionProfile`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivePermissionProfile {
    /// Parent profile identifier from the selected permissions profile's `extends` setting, when present.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extends: Option<String>,
    /// Identifier from `default_permissions` or the implicit built-in default, such as `:workspace` or a user-defined `[permissions.<id>]` profile.
    pub id: String,
}

pub type ReasoningEffort = String;

/// `NetworkAccess`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NetworkAccess {
    #[serde(rename = "restricted")]
    Restricted,
    #[serde(rename = "enabled")]
    Enabled,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `SandboxPolicy`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum SandboxPolicy {
    #[serde(rename = "dangerFullAccess")]
    DangerFullAccess,
    #[serde(rename = "readOnly")]
    ReadOnly {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        network_access: Option<bool>,
    },
    #[serde(rename = "externalSandbox")]
    ExternalSandbox {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        network_access: Option<NetworkAccess>,
    },
    #[serde(rename = "workspaceWrite")]
    WorkspaceWrite {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        exclude_slash_tmp: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        exclude_tmpdir_env_var: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        network_access: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        writable_roots: Option<Vec<AbsolutePathBuf>>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

pub type ThreadExtra = serde_json::Value;

/// `GitInfo`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GitInfo {
    /// `branch`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub branch: Option<String>,
    /// `originUrl`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin_url: Option<String>,
    /// `sha`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
}

/// An independently persisted, user-visible thread section.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadSection {
    /// Opaque UUIDv7 identity that remains stable when the section is renamed.
    pub id: String,
    /// The current user-visible section name.
    pub name: String,
}

pub type AgentPath = String;

pub type ThreadId = String;

/// `SubAgentSourceThreadSpawnThreadSpawn`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SubAgentSourceThreadSpawnThreadSpawn {
    /// `agent_nickname`.
    #[serde(
        rename = "agent_nickname",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_nickname: Option<String>,
    /// `agent_path`.
    #[serde(
        rename = "agent_path",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_path: Option<AgentPath>,
    /// `agent_role`.
    #[serde(
        rename = "agent_role",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_role: Option<String>,
    /// `depth`.
    pub depth: i64,
    /// `parent_thread_id`.
    #[serde(rename = "parent_thread_id")]
    pub parent_thread_id: ThreadId,
}

/// `SubAgentSource`.
pub type SubAgentSource = crate::agents::codex::tolerant::Tolerant<SubAgentSourceKnown>;

/// The variants of `SubAgentSource` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SubAgentSourceKnown {
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "compact")]
    Compact,
    #[serde(rename = "memory_consolidation")]
    MemoryConsolidation,
    #[serde(rename = "thread_spawn")]
    ThreadSpawn(SubAgentSourceThreadSpawnThreadSpawn),
    #[serde(rename = "other")]
    Other(String),
}

/// `SessionSource`.
pub type SessionSource = crate::agents::codex::tolerant::Tolerant<SessionSourceKnown>;

/// The variants of `SessionSource` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SessionSourceKnown {
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "vscode")]
    Vscode,
    #[serde(rename = "exec")]
    Exec,
    #[serde(rename = "appServer")]
    AppServer,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "custom")]
    Custom(String),
    #[serde(rename = "subAgent")]
    SubAgent(SubAgentSource),
}

/// `ThreadActiveFlag`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ThreadActiveFlag {
    #[serde(rename = "waitingOnApproval")]
    WaitingOnApproval,
    #[serde(rename = "waitingOnUserInput")]
    WaitingOnUserInput,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `ThreadStatus`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ThreadStatus {
    #[serde(rename = "notLoaded")]
    NotLoaded,
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "systemError")]
    SystemError,
    #[serde(rename = "active")]
    Active { active_flags: Vec<ThreadActiveFlag> },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `CodexErrorInfoHttpConnectionFailedHttpConnectionFailed`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexErrorInfoHttpConnectionFailedHttpConnectionFailed {
    /// `httpStatusCode`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<u64>,
}

/// `CodexErrorInfoResponseStreamConnectionFailedResponseStreamConnectionFailed`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexErrorInfoResponseStreamConnectionFailedResponseStreamConnectionFailed {
    /// `httpStatusCode`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<u64>,
}

/// `CodexErrorInfoResponseStreamDisconnectedResponseStreamDisconnected`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexErrorInfoResponseStreamDisconnectedResponseStreamDisconnected {
    /// `httpStatusCode`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<u64>,
}

/// `CodexErrorInfoResponseTooManyFailedAttemptsResponseTooManyFailedAttempts`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexErrorInfoResponseTooManyFailedAttemptsResponseTooManyFailedAttempts {
    /// `httpStatusCode`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<u64>,
}

/// `NonSteerableTurnKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NonSteerableTurnKind {
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "compact")]
    Compact,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `CodexErrorInfoActiveTurnNotSteerableActiveTurnNotSteerable`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexErrorInfoActiveTurnNotSteerableActiveTurnNotSteerable {
    /// `turnKind`.
    pub turn_kind: NonSteerableTurnKind,
}

/// This translation layer make sure that we expose codex error code in camel case.
///
/// When an upstream HTTP status is available (for example, from the Responses API or a provider), it is forwarded in `httpStatusCode` on the relevant `codexErrorInfo` variant.
pub type CodexErrorInfo = crate::agents::codex::tolerant::Tolerant<CodexErrorInfoKnown>;

/// The variants of `CodexErrorInfo` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CodexErrorInfoKnown {
    #[serde(rename = "contextWindowExceeded")]
    ContextWindowExceeded,
    #[serde(rename = "sessionBudgetExceeded")]
    SessionBudgetExceeded,
    #[serde(rename = "usageLimitExceeded")]
    UsageLimitExceeded,
    #[serde(rename = "serverOverloaded")]
    ServerOverloaded,
    #[serde(rename = "cyberPolicy")]
    CyberPolicy,
    #[serde(rename = "internalServerError")]
    InternalServerError,
    #[serde(rename = "unauthorized")]
    Unauthorized,
    #[serde(rename = "badRequest")]
    BadRequest,
    #[serde(rename = "threadRollbackFailed")]
    ThreadRollbackFailed,
    #[serde(rename = "sandboxError")]
    SandboxError,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "httpConnectionFailed")]
    HttpConnectionFailed(CodexErrorInfoHttpConnectionFailedHttpConnectionFailed),
    /// Failed to connect to the response SSE stream.
    #[serde(rename = "responseStreamConnectionFailed")]
    ResponseStreamConnectionFailed(
        CodexErrorInfoResponseStreamConnectionFailedResponseStreamConnectionFailed,
    ),
    /// The response SSE stream disconnected in the middle of a turn before completion.
    #[serde(rename = "responseStreamDisconnected")]
    ResponseStreamDisconnected(CodexErrorInfoResponseStreamDisconnectedResponseStreamDisconnected),
    /// Reached the retry limit for responses.
    #[serde(rename = "responseTooManyFailedAttempts")]
    ResponseTooManyFailedAttempts(
        CodexErrorInfoResponseTooManyFailedAttemptsResponseTooManyFailedAttempts,
    ),
    /// Returned when `turn/start` or `turn/steer` is submitted while the current active turn cannot accept same-turn steering, for example `/review` or manual `/compact`.
    #[serde(rename = "activeTurnNotSteerable")]
    ActiveTurnNotSteerable(CodexErrorInfoActiveTurnNotSteerableActiveTurnNotSteerable),
}

/// `TurnError`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnError {
    /// `additionalDetails`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_details: Option<String>,
    /// `codexErrorInfo`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub codex_error_info: Option<CodexErrorInfo>,
    /// `message`.
    pub message: String,
}

/// `ByteRange`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ByteRange {
    /// `end`.
    pub end: u64,
    /// `start`.
    pub start: u64,
}

/// `TextElement`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TextElement {
    /// Byte range in the parent `text` buffer that this element occupies.
    pub byte_range: ByteRange,
    /// Optional human-readable placeholder for the element, displayed in the UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
}

/// `ImageDetail`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ImageDetail {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "low")]
    Low,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "original")]
    Original,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `UserInput`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum UserInput {
    #[serde(rename = "text")]
    Text {
        text: String,
        #[serde(
            rename = "text_elements",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        text_elements: Option<Vec<TextElement>>,
    },
    #[serde(rename = "image")]
    Image {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        detail: Option<ImageDetail>,
        url: String,
    },
    #[serde(rename = "localImage")]
    LocalImage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        detail: Option<ImageDetail>,
        path: String,
    },
    #[serde(rename = "audio")]
    Audio { url: String },
    #[serde(rename = "localAudio")]
    LocalAudio { path: String },
    #[serde(rename = "skill")]
    Skill { name: String, path: String },
    #[serde(rename = "mention")]
    Mention { name: String, path: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `HookPromptFragment`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HookPromptFragment {
    /// `hookRunId`.
    pub hook_run_id: String,
    /// `text`.
    pub text: String,
}
