// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the threads methods, part 3.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `ContentItem`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ContentItem {
    #[serde(rename = "input_text")]
    InputText { text: String },
    #[serde(rename = "input_image")]
    InputImage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        detail: Option<ImageDetail>,
        #[serde(rename = "image_url")]
        image_url: String,
    },
    #[serde(rename = "input_audio")]
    InputAudio {
        #[serde(rename = "audio_url")]
        audio_url: String,
    },
    #[serde(rename = "output_text")]
    OutputText { text: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// Internal Responses API passthrough metadata copied into underlying chat messages.
///
/// Responses API strongly types this payload. Do not modify it without first getting API approval and making the corresponding Responses API change.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InternalChatMessageMetadataPassthrough {
    /// `turn_id`.
    #[serde(rename = "turn_id", default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}

/// `AgentMessageInputContent`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum AgentMessageInputContent {
    #[serde(rename = "input_text")]
    InputText { text: String },
    #[serde(rename = "encrypted_content")]
    EncryptedContent {
        #[serde(rename = "encrypted_content")]
        encrypted_content: String,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `ReasoningItemContent`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ReasoningItemContent {
    #[serde(rename = "reasoning_text")]
    ReasoningText { text: String },
    #[serde(rename = "text")]
    Text { text: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `SummaryTextReasoningItemReasoningSummaryType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SummaryTextReasoningItemReasoningSummaryType {
    #[serde(rename = "summary_text")]
    SummaryText,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `SummaryTextReasoningItemReasoningSummary`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SummaryTextReasoningItemReasoningSummary {
    /// `text`.
    pub text: String,
    /// `type`.
    pub r#type: SummaryTextReasoningItemReasoningSummaryType,
}

pub type ReasoningItemReasoningSummary = SummaryTextReasoningItemReasoningSummary;

/// `ExecLocalShellActionType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExecLocalShellActionType {
    #[serde(rename = "exec")]
    Exec,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `ExecLocalShellAction`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecLocalShellAction {
    /// `command`.
    pub command: Vec<String>,
    /// `env`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
    /// `timeout_ms`.
    #[serde(
        rename = "timeout_ms",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout_ms: Option<u64>,
    /// `type`.
    pub r#type: ExecLocalShellActionType,
    /// `user`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// `working_directory`.
    #[serde(
        rename = "working_directory",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub working_directory: Option<String>,
}

pub type LocalShellAction = ExecLocalShellAction;

/// `LocalShellStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LocalShellStatus {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "incomplete")]
    Incomplete,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `FunctionCallOutputBody`.
pub type FunctionCallOutputBody = serde_json::Value;

/// `ResponsesApiWebSearchAction`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ResponsesApiWebSearchAction {
    #[serde(rename = "search")]
    Search {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        queries: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        query: Option<String>,
    },
    #[serde(rename = "open_page")]
    OpenPage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "find_in_page")]
    FindInPage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pattern: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "other")]
    Other,
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `ResponseItem`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ResponseItem {
    #[serde(rename = "message")]
    Message {
        content: Vec<ContentItem>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        phase: Option<MessagePhase>,
        role: String,
    },
    #[serde(rename = "agent_message")]
    AgentMessage {
        author: String,
        content: Vec<AgentMessageInputContent>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        recipient: String,
    },
    #[serde(rename = "reasoning")]
    Reasoning {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content: Option<Vec<ReasoningItemContent>>,
        #[serde(
            rename = "encrypted_content",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        encrypted_content: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        summary: Vec<ReasoningItemReasoningSummary>,
    },
    #[serde(rename = "local_shell_call")]
    LocalShellCall {
        action: LocalShellAction,
        #[serde(rename = "call_id", default, skip_serializing_if = "Option::is_none")]
        call_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        status: LocalShellStatus,
    },
    #[serde(rename = "function_call")]
    FunctionCall {
        arguments: String,
        #[serde(rename = "call_id")]
        call_id: String,
        #[serde(
            rename = "encrypted_function_args",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        encrypted_function_args: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        namespace: Option<String>,
    },
    #[serde(rename = "tool_search_call")]
    ToolSearchCall {
        arguments: serde_json::Value,
        #[serde(rename = "call_id", default, skip_serializing_if = "Option::is_none")]
        call_id: Option<String>,
        execution: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<String>,
    },
    #[serde(rename = "function_call_output")]
    FunctionCallOutput {
        #[serde(rename = "call_id")]
        call_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        output: FunctionCallOutputBody,
    },
    #[serde(rename = "custom_tool_call")]
    CustomToolCall {
        #[serde(rename = "call_id")]
        call_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        input: String,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        name: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        namespace: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<String>,
    },
    #[serde(rename = "custom_tool_call_output")]
    CustomToolCallOutput {
        #[serde(rename = "call_id")]
        call_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        output: FunctionCallOutputBody,
    },
    #[serde(rename = "tool_search_output")]
    ToolSearchOutput {
        #[serde(rename = "call_id", default, skip_serializing_if = "Option::is_none")]
        call_id: Option<String>,
        execution: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        status: String,
        tools: Vec<serde_json::Value>,
    },
    #[serde(rename = "web_search_call")]
    WebSearchCall {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        action: Option<ResponsesApiWebSearchAction>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        status: Option<String>,
    },
    #[serde(rename = "image_generation_call")]
    ImageGenerationCall {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
        result: String,
        #[serde(
            rename = "revised_prompt",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        revised_prompt: Option<String>,
        status: String,
    },
    #[serde(rename = "compaction")]
    Compaction {
        #[serde(rename = "encrypted_content")]
        encrypted_content: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
    },
    #[serde(rename = "compaction_trigger")]
    CompactionTrigger,
    #[serde(rename = "context_compaction")]
    ContextCompaction {
        #[serde(
            rename = "encrypted_content",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        encrypted_content: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(
            rename = "internal_chat_message_metadata_passthrough",
            default,
            skip_serializing_if = "Option::is_none"
        )]
        internal_chat_message_metadata_passthrough: Option<InternalChatMessageMetadataPassthrough>,
    },
    #[serde(rename = "other")]
    Other,
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `SortDirection`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SortDirection {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `ThreadResumeInitialTurnsPageParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadResumeInitialTurnsPageParams {
    /// How much item detail to include for each returned turn; defaults to summary.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items_view: Option<TurnItemsView>,
    /// Optional turn page size.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
    /// Optional turn pagination direction; defaults to descending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_direction: Option<SortDirection>,
}

/// There are three ways to resume a thread: 1. By thread_id: load the thread from disk by thread_id and resume it. 2. By history: instantiate the thread from memory and resume it. 3. By path: load the thread from disk by path and resume it.
///
/// For non-running threads, the precedence is: history > non-empty path > thread_id. If using history or a non-empty path for a non-running thread, the thread_id param will be ignored.
///
/// If thread_id identifies a running thread, app-server rejoins that thread and treats a non-empty path as a consistency check against the active rollout path. Empty string path values are treated as absent.
///
/// Prefer using thread_id whenever possible.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadResumeParams {
    /// `approvalPolicy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<AskForApproval>,
    /// Override where approval requests are routed for review on this thread and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvals_reviewer: Option<ApprovalsReviewer>,
    /// `baseInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_instructions: Option<String>,
    /// `config`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// `cwd`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// `developerInstructions`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub developer_instructions: Option<String>,
    /// When true, return only thread metadata and live-resume state without populating `thread.turns`. This is useful when the client plans to call `thread/turns/list` immediately after resuming.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude_turns: Option<bool>,
    /// [UNSTABLE] FOR CODEX CLOUD - DO NOT USE. If specified, the thread will be resumed with the provided history instead of loaded from disk.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<ResponseItem>>,
    /// When present, include a `thread/turns/list` page in the resume response so clients can bootstrap recent turns without a second request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initial_turns_page: Option<ThreadResumeInitialTurnsPageParams>,
    /// Configuration overrides for the resumed thread, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// `modelProvider`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_provider: Option<String>,
    /// [UNSTABLE] Specify the rollout path to resume from. If specified for a non-running thread, the thread_id param will be ignored. If thread_id identifies a running thread, the path must match the active rollout path.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Named profile id for the resumed thread. Cannot be combined with `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// `personality`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personality: Option<Personality>,
    /// Replace the thread's runtime workspace roots. Paths must be absolute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// `sandbox`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<SandboxMode>,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `threadId`.
    pub thread_id: String,
}

/// `TurnsPage`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnsPage {
    /// `backwardsCursor`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backwards_cursor: Option<String>,
    /// `data`.
    pub data: Vec<Turn>,
    /// `nextCursor`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// `ThreadResumeResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadResumeResponse {
    /// Named or implicit built-in profile that produced the active permissions, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_permission_profile: Option<ActivePermissionProfile>,
    /// `approvalPolicy`.
    pub approval_policy: AskForApproval,
    /// Reviewer currently used for approval requests on this thread.
    pub approvals_reviewer: ApprovalsReviewer,
    /// `cwd`.
    pub cwd: AbsolutePathBuf,
    /// `thread/turns/list` page returned when requested by `initialTurnsPage`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub initial_turns_page: Option<TurnsPage>,
    /// Environment-native paths to instruction source files currently loaded for this thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instruction_sources: Option<Vec<LegacyAppPathString>>,
    /// Opaque head cursor for hydrating paginated items backwards.
    ///
    /// Pass this as `cursor` to `thread/items/list` with `sortDirection: "desc"`. The first page includes the cursor's head item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items_backwards_cursor: Option<String>,
    /// `model`.
    pub model: String,
    /// `modelProvider`.
    pub model_provider: String,
    /// @deprecated Always `explicitRequestOnly`. Use `reasoningEffort` for Ultra behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// `reasoningEffort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Thread-scoped runtime workspace roots used to materialize `:workspace_roots`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.
    pub sandbox: SandboxPolicy,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `thread`.
    pub thread: Thread,
    /// Opaque head cursor for hydrating paginated turns backwards.
    ///
    /// Pass this as `cursor` to `thread/turns/list` with `sortDirection: "desc"`. The first page includes the cursor's head turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turns_backwards_cursor: Option<String>,
}

/// `ThreadReadParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadReadParams {
    /// When true, include turns and their items from rollout history.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_turns: Option<bool>,
    /// `threadId`.
    pub thread_id: String,
}

/// `ThreadReadResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadReadResponse {
    /// `thread`.
    pub thread: Thread,
}

/// `ThreadItemsListParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadItemsListParams {
    /// Opaque cursor to pass to the next call to continue after the last item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Optional item page size.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
    /// Optional item pagination direction; defaults to ascending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sort_direction: Option<SortDirection>,
    /// `threadId`.
    pub thread_id: String,
    /// Optional turn id to filter by. When omitted, returns items across the thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
}

/// `ThreadItemEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadItemEntry {
    /// `item`.
    pub item: ThreadItem,
    /// Turn containing this item.
    pub turn_id: String,
}

/// `ThreadItemsListResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadItemsListResponse {
    /// Opaque cursor to pass as `cursor` when reversing `sortDirection`. This is only populated when the page contains at least one item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backwards_cursor: Option<String>,
    /// `data`.
    pub data: Vec<ThreadItemEntry>,
    /// Opaque cursor to pass to the next call to continue after the last item. if None, there are no more items to return.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// Initial collaboration mode to use when the TUI starts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ModeKind {
    #[serde(rename = "plan")]
    Plan,
    #[serde(rename = "default")]
    Default,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// Settings for a collaboration mode.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Settings {
    /// `developer_instructions`.
    #[serde(
        rename = "developer_instructions",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub developer_instructions: Option<String>,
    /// `model`.
    pub model: String,
    /// `reasoning_effort`.
    #[serde(
        rename = "reasoning_effort",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reasoning_effort: Option<ReasoningEffort>,
}

/// Collaboration mode for a Codex session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollaborationMode {
    /// `mode`.
    pub mode: ModeKind,
    /// `settings`.
    pub settings: Settings,
}

/// A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. See https://platform.openai.com/docs/guides/reasoning?api-mode=responses#reasoning-summaries
pub type ReasoningSummary = crate::agents::codex::tolerant::Tolerant<ReasoningSummaryKnown>;

/// The variants of `ReasoningSummary` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum ReasoningSummaryKnown {
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "concise")]
    Concise,
    #[serde(rename = "detailed")]
    Detailed,
    /// Option to disable reasoning summaries.
    #[serde(rename = "none")]
    None,
}

/// `ThreadSettingsUpdateParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadSettingsUpdateParams {
    /// Override the approval policy for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<AskForApproval>,
    /// Override where approval requests are routed for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvals_reviewer: Option<ApprovalsReviewer>,
    /// EXPERIMENTAL - Set a pre-set collaboration mode for subsequent turns.
    ///
    /// For `collaboration_mode.settings.developer_instructions`, `null` means "use the built-in instructions for the selected mode".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collaboration_mode: Option<CollaborationMode>,
    /// Override the working directory for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Override the reasoning effort for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// Override the model for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// @deprecated Ignored. Use `effort: "ultra"` for proactive multi-agent behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// Select a named permissions profile id for subsequent turns. Cannot be combined with `sandboxPolicy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// Override the personality for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personality: Option<Personality>,
    /// Override the sandbox policy for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox_policy: Option<SandboxPolicy>,
    /// Override the service tier for subsequent turns. `null` clears the current service tier; omission leaves it unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// Override the reasoning summary for subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<ReasoningSummary>,
    /// `threadId`.
    pub thread_id: String,
}

pub type ThreadSettingsUpdateResponse = serde_json::Value;

/// `ThreadCompactStartParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadCompactStartParams {
    /// `threadId`.
    pub thread_id: String,
}

pub type ThreadCompactStartResponse = serde_json::Value;
