// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the threads methods, part 2.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `MemoryCitationEntry`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryCitationEntry {
    /// `lineEnd`.
    pub line_end: u64,
    /// `lineStart`.
    pub line_start: u64,
    /// `note`.
    pub note: String,
    /// `path`.
    pub path: String,
}

/// `MemoryCitation`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryCitation {
    /// `entries`.
    pub entries: Vec<MemoryCitationEntry>,
    /// `threadIds`.
    pub thread_ids: Vec<String>,
}

/// Classifies an assistant message as interim commentary or final answer text.
///
/// Providers do not emit this consistently, so callers must treat `None` as "phase unknown" and keep compatibility behavior for legacy models.
pub type MessagePhase = crate::agents::codex::tolerant::Tolerant<MessagePhaseKnown>;

/// The variants of `MessagePhase` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum MessagePhaseKnown {
    /// Mid-turn assistant text (for example preamble/progress narration).
    ///
    /// Additional tool calls or assistant output may follow before turn completion.
    #[serde(rename = "commentary")]
    Commentary,
    /// The assistant's terminal answer text for the current turn.
    #[serde(rename = "final_answer")]
    FinalAnswer,
}

/// `CommandAction`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum CommandAction {
    #[serde(rename = "read")]
    Read {
        command: String,
        name: String,
        path: LegacyAppPathString,
    },
    #[serde(rename = "listFiles")]
    ListFiles {
        command: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        path: Option<String>,
    },
    #[serde(rename = "search")]
    Search {
        command: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        path: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        query: Option<String>,
    },
    #[serde(rename = "unknown")]
    Unknown { command: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unrecognized,
}

/// `CommandExecutionSource`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommandExecutionSource {
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "userShell")]
    UserShell,
    #[serde(rename = "unifiedExecStartup")]
    UnifiedExecStartup,
    #[serde(rename = "unifiedExecInteraction")]
    UnifiedExecInteraction,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `CommandExecutionStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommandExecutionStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "declined")]
    Declined,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `PatchChangeKind`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum PatchChangeKind {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "update")]
    Update {
        #[serde(rename = "move_path", default, skip_serializing_if = "Option::is_none")]
        move_path: Option<String>,
    },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `FileUpdateChange`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FileUpdateChange {
    /// `diff`.
    pub diff: String,
    /// `kind`.
    pub kind: PatchChangeKind,
    /// `path`.
    pub path: String,
}

/// `PatchApplyStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PatchApplyStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "declined")]
    Declined,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `McpToolCallAppContext`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolCallAppContext {
    /// `actionName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_name: Option<String>,
    /// `appName`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_name: Option<String>,
    /// `connectorId`.
    pub connector_id: String,
    /// `linkId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub link_id: Option<String>,
    /// `resourceUri`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resource_uri: Option<String>,
}

/// `McpToolCallError`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolCallError {
    /// `message`.
    pub message: String,
}

/// `McpToolCallResult`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct McpToolCallResult {
    /// `_meta`.
    #[serde(rename = "_meta", default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
    /// `content`.
    pub content: Vec<serde_json::Value>,
    /// `structuredContent`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub structured_content: Option<serde_json::Value>,
}

/// `McpToolCallStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum McpToolCallStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `DynamicToolCallOutputContentItem`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum DynamicToolCallOutputContentItem {
    #[serde(rename = "inputText")]
    InputText { text: String },
    #[serde(rename = "inputImage")]
    InputImage { image_url: String },
    #[serde(rename = "inputAudio")]
    InputAudio { audio_url: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `DynamicToolCallStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum DynamicToolCallStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `CollabAgentToolCallStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CollabAgentToolCallStatus {
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `CollabAgentTool`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CollabAgentTool {
    #[serde(rename = "spawnAgent")]
    SpawnAgent,
    #[serde(rename = "sendInput")]
    SendInput,
    #[serde(rename = "resumeAgent")]
    ResumeAgent,
    #[serde(rename = "wait")]
    Wait,
    #[serde(rename = "closeAgent")]
    CloseAgent,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `SubAgentActivityKind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SubAgentActivityKind {
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "interacted")]
    Interacted,
    #[serde(rename = "interrupted")]
    Interrupted,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `WebSearchAction`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum WebSearchAction {
    #[serde(rename = "search")]
    Search {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        queries: Option<Vec<String>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        query: Option<String>,
    },
    #[serde(rename = "openPage")]
    OpenPage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "findInPage")]
    FindInPage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pattern: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "other")]
    Other,
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `ThreadItem`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub enum ThreadItem {
    #[serde(rename = "userMessage")]
    UserMessage {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        client_id: Option<String>,
        content: Vec<UserInput>,
        id: String,
    },
    #[serde(rename = "hookPrompt")]
    HookPrompt {
        fragments: Vec<HookPromptFragment>,
        id: String,
    },
    #[serde(rename = "agentMessage")]
    AgentMessage {
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        memory_citation: Option<MemoryCitation>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        phase: Option<MessagePhase>,
        text: String,
    },
    /// EXPERIMENTAL - proposed plan item content. The completed plan item is authoritative and may not match the concatenation of `PlanDelta` text.
    #[serde(rename = "plan")]
    Plan { id: String, text: String },
    #[serde(rename = "reasoning")]
    Reasoning {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content: Option<Vec<String>>,
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        summary: Option<Vec<String>>,
    },
    #[serde(rename = "commandExecution")]
    CommandExecution {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        aggregated_output: Option<String>,
        command: String,
        command_actions: Vec<CommandAction>,
        cwd: LegacyAppPathString,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        duration_ms: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        exit_code: Option<i64>,
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        plugin_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        process_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        script_path: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        source: Option<CommandExecutionSource>,
        status: CommandExecutionStatus,
    },
    #[serde(rename = "fileChange")]
    FileChange {
        changes: Vec<FileUpdateChange>,
        id: String,
        status: PatchApplyStatus,
    },
    #[serde(rename = "mcpToolCall")]
    McpToolCall {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        app_context: Option<Box<McpToolCallAppContext>>,
        arguments: serde_json::Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        duration_ms: Option<i64>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        error: Option<McpToolCallError>,
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        mcp_app_resource_uri: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        plugin_id: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        read_only_hint: Option<bool>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        result: Option<Box<McpToolCallResult>>,
        server: String,
        status: McpToolCallStatus,
        tool: String,
    },
    #[serde(rename = "dynamicToolCall")]
    DynamicToolCall {
        arguments: serde_json::Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content_items: Option<Vec<DynamicToolCallOutputContentItem>>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        duration_ms: Option<i64>,
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        namespace: Option<String>,
        status: DynamicToolCallStatus,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        success: Option<bool>,
        tool: String,
    },
    #[serde(rename = "collabAgentToolCall")]
    CollabAgentToolCall {
        agents_states: serde_json::Value,
        id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        model: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        prompt: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reasoning_effort: Option<ReasoningEffort>,
        receiver_thread_ids: Vec<String>,
        sender_thread_id: String,
        status: CollabAgentToolCallStatus,
        tool: CollabAgentTool,
    },
    #[serde(rename = "subAgentActivity")]
    SubAgentActivity {
        agent_path: String,
        agent_thread_id: String,
        id: String,
        kind: SubAgentActivityKind,
    },
    #[serde(rename = "webSearch")]
    WebSearch {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        action: Option<WebSearchAction>,
        id: String,
        query: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        results: Option<Vec<serde_json::Value>>,
    },
    #[serde(rename = "imageView")]
    ImageView {
        id: String,
        path: LegacyAppPathString,
    },
    /// Display item emitted by the interruptible `clock.sleep` tool.
    #[serde(rename = "sleep")]
    Sleep { duration_ms: u64, id: String },
    #[serde(rename = "imageGeneration")]
    ImageGeneration {
        id: String,
        result: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        revised_prompt: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        saved_path: Option<AbsolutePathBuf>,
        status: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        transparent_background: Option<bool>,
    },
    #[serde(rename = "enteredReviewMode")]
    EnteredReviewMode { id: String, review: String },
    #[serde(rename = "exitedReviewMode")]
    ExitedReviewMode { id: String, review: String },
    #[serde(rename = "contextCompaction")]
    ContextCompaction { id: String },
    /// A variant this build does not know, kept so one new value cannot
    /// make a whole class of frames invisible (§4.5 rule 1).
    #[serde(other)]
    Unknown,
}

/// `TurnItemsView`.
pub type TurnItemsView = crate::agents::codex::tolerant::Tolerant<TurnItemsViewKnown>;

/// The variants of `TurnItemsView` this build knows.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum TurnItemsViewKnown {
    /// `items` was not loaded for this turn. The field is intentionally empty.
    #[serde(rename = "notLoaded")]
    NotLoaded,
    /// `items` contains only a display summary for this turn.
    #[serde(rename = "summary")]
    Summary,
    /// `items` contains every ThreadItem available from persisted app-server history for this turn.
    #[serde(rename = "full")]
    Full,
}

/// `TurnStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnStatus {
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "inProgress")]
    InProgress,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `Turn`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Turn {
    /// Unix timestamp (in seconds) when the turn completed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<i64>,
    /// Duration between turn start and completion in milliseconds, if known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    /// Only populated when the Turn's status is failed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<TurnError>,
    /// Identifier for this turn. Codex-generated turn IDs are UUIDv7.
    pub id: String,
    /// Thread items currently included in this turn payload.
    pub items: Vec<ThreadItem>,
    /// Describes how much of `items` has been loaded for this turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub items_view: Option<TurnItemsView>,
    /// Unix timestamp (in seconds) when the turn started.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<i64>,
    /// `status`.
    pub status: TurnStatus,
}

/// `Thread`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Thread {
    /// Optional random unique nickname assigned to an AgentControl-spawned sub-agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_nickname: Option<String>,
    /// Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_role: Option<String>,
    /// Whether the app server accepts direct turn input for this loaded thread. `None` means the capability is unavailable, such as for an unloaded stored thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub can_accept_direct_input: Option<bool>,
    /// Version of the CLI that created the thread.
    pub cli_version: String,
    /// Unix timestamp (in seconds) when the thread was created.
    pub created_at: i64,
    /// Working directory captured for the thread.
    pub cwd: AbsolutePathBuf,
    /// Whether the thread is ephemeral and should not be materialized on disk.
    pub ephemeral: bool,
    /// Optional implementation-specific thread data.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra: Option<ThreadExtra>,
    /// Source thread id when this thread was created by forking another thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub forked_from_id: Option<String>,
    /// Optional Git metadata captured when the thread was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_info: Option<GitInfo>,
    /// Persisted thread history contract selected when this thread was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub history_mode: Option<ThreadHistoryMode>,
    /// Identifier for this thread. Codex-generated thread IDs are UUIDv7.
    pub id: String,
    /// Model provider used for this thread (for example, 'openai').
    pub model_provider: String,
    /// Optional user-facing thread title.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The ID of the parent thread. This will only be set if this thread is a subagent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_thread_id: Option<String>,
    /// [UNSTABLE] Path to the thread on disk.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Usually the first user message in the thread, if available.
    pub preview: String,
    /// Unix timestamp (in seconds) used for thread recency ordering.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recency_at: Option<i64>,
    /// The independently persisted section selected for this thread, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub section: Option<ThreadSection>,
    /// Unix timestamp in seconds when the thread entered its current section.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub section_entered_at: Option<i64>,
    /// Session id shared by threads that belong to the same session tree.
    pub session_id: String,
    /// Origin of the thread (CLI, VSCode, codex exec, codex app-server, etc.).
    pub source: SessionSource,
    /// Current runtime status for the thread.
    pub status: ThreadStatus,
    /// Optional analytics source classification for this thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thread_source: Option<ThreadSource>,
    /// Only populated on `thread/resume`, `thread/rollback`, `thread/fork`, and `thread/read` (when `includeTurns` is true) responses. For all other responses and notifications returning a Thread, the turns field will be an empty list.
    pub turns: Vec<Turn>,
    /// Unix timestamp (in seconds) when the thread was last updated.
    pub updated_at: i64,
}

/// `ThreadStartResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThreadStartResponse {
    /// Named or implicit built-in profile that produced the active permissions, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_permission_profile: Option<ActivePermissionProfile>,
    /// `approvalPolicy`.
    pub approval_policy: AskForApproval,
    /// Reviewer currently used for approval requests on this thread.
    pub approvals_reviewer: ApprovalsReviewer,
    /// `cwd`.
    pub cwd: AbsolutePathBuf,
    /// Environment-native paths to instruction source files currently loaded for this thread.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instruction_sources: Option<Vec<LegacyAppPathString>>,
    /// `model`.
    pub model: String,
    /// `modelProvider`.
    pub model_provider: String,
    /// @deprecated Always `explicitRequestOnly`. Use `reasoningEffort` for Ultra behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// `reasoningEffort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<ReasoningEffort>,
    /// Thread-scoped runtime workspace roots used to materialize `:workspace_roots`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// Legacy sandbox policy retained for compatibility. Experimental clients should prefer `activePermissionProfile` for profile provenance.
    pub sandbox: SandboxPolicy,
    /// `serviceTier`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// `thread`.
    pub thread: Thread,
}
