// @generated by scripts/generate-codex-wire.py — DO NOT EDIT BY HAND.
//
// Source: `codex app-server generate-json-schema --out <dir> --experimental`
// Generated from: codex-cli 0.147.0
//
// Regenerate after every Codex upgrade and read the diff: both harnesses add
// fields and enum values without a version bump, and this file is where that shows.
//! Generated Codex wire types reached from the turns methods.

use serde::{Deserialize, Serialize};

// Every part re-exports through `wire::mod`, so the glob below is what lets
// this part name a type another part declares.
use super::*;

/// `TurnStartParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStartParams {
    /// Optional client-provided context fragments keyed by an opaque source identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<serde_json::Value>,
    /// Override the approval policy for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_policy: Option<AskForApproval>,
    /// Override where approval requests are routed for review on this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approvals_reviewer: Option<ApprovalsReviewer>,
    /// `clientUserMessageId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_user_message_id: Option<String>,
    /// EXPERIMENTAL - Set a pre-set collaboration mode. Takes precedence over model, reasoning_effort, and developer instructions if set.
    ///
    /// For `collaboration_mode.settings.developer_instructions`, `null` means "use the built-in instructions for the selected mode".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub collaboration_mode: Option<CollaborationMode>,
    /// Override the working directory for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    /// Override the reasoning effort for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// Optional environments for this turn and subsequent turns.
    ///
    /// Omitted uses the thread sticky environments. Empty disables environment access for this turn. Non-empty selects the first environment as the current turn environment for this turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environments: Option<Vec<TurnEnvironmentParams>>,
    /// `input`.
    pub input: Vec<UserInput>,
    /// Override the model for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// @deprecated Ignored. Use `effort: "ultra"` for proactive multi-agent behavior.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_agent_mode: Option<MultiAgentMode>,
    /// Optional JSON Schema used to constrain the final assistant message for this turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_schema: Option<serde_json::Value>,
    /// Select a named permissions profile id for this turn and subsequent turns. Cannot be combined with `sandboxPolicy`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    /// Override the personality for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub personality: Option<Personality>,
    /// Optional metadata to enrich Codex's ResponsesAPI turn metadata.
    ///
    /// Entries are flattened into the JSON string sent as `client_metadata["x-codex-turn-metadata"]` on ResponsesAPI HTTP and websocket requests.
    ///
    /// They are not sent as top-level ResponsesAPI `client_metadata` keys, and reserved keys such as `session_id`, `thread_id`, `turn_id`, and `window_id` cannot be overridden.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub responsesapi_client_metadata: Option<serde_json::Value>,
    /// Replace the thread's runtime workspace roots for this turn and subsequent turns. Paths must be absolute.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_workspace_roots: Option<Vec<AbsolutePathBuf>>,
    /// Override the sandbox policy for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sandbox_policy: Option<SandboxPolicy>,
    /// Override the service tier for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<String>,
    /// Override the reasoning summary for this turn and subsequent turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<ReasoningSummary>,
    /// `threadId`.
    pub thread_id: String,
}

/// `TurnStartResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStartResponse {
    /// `turn`.
    pub turn: Turn,
}

/// `TurnSteerParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnSteerParams {
    /// Optional client-provided context fragments keyed by an opaque source identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub additional_context: Option<serde_json::Value>,
    /// `clientUserMessageId`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_user_message_id: Option<String>,
    /// Required active turn id precondition. The request fails when it does not match the currently active turn.
    pub expected_turn_id: String,
    /// `input`.
    pub input: Vec<UserInput>,
    /// Optional metadata to enrich Codex's ResponsesAPI turn metadata.
    ///
    /// Entries are flattened into the JSON string sent as `client_metadata["x-codex-turn-metadata"]` on ResponsesAPI HTTP and websocket requests.
    ///
    /// They are not sent as top-level ResponsesAPI `client_metadata` keys, and reserved keys such as `session_id`, `thread_id`, `turn_id`, and `window_id` cannot be overridden.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub responsesapi_client_metadata: Option<serde_json::Value>,
    /// `threadId`.
    pub thread_id: String,
}

/// `TurnSteerResponse`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnSteerResponse {
    /// `turnId`.
    pub turn_id: String,
}

/// `TurnInterruptParams`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnInterruptParams {
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

pub type TurnInterruptResponse = serde_json::Value;

/// `TurnStartedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnStartedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `turn`.
    pub turn: Turn,
}

/// `TurnCompletedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnCompletedNotification {
    /// `threadId`.
    pub thread_id: String,
    /// `turn`.
    pub turn: Turn,
}

/// Notification that the turn-level unified diff has changed. Contains the latest aggregated diff across all file changes in the turn.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnDiffUpdatedNotification {
    /// `diff`.
    pub diff: String,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `TurnPlanStepStatus`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnPlanStepStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "inProgress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    /// A value this build does not know. Never a decode failure (§4.5).
    #[serde(other)]
    Unknown,
}

/// `TurnPlanStep`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnPlanStep {
    /// `status`.
    pub status: TurnPlanStepStatus,
    /// `step`.
    pub step: String,
}

/// `TurnPlanUpdatedNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnPlanUpdatedNotification {
    /// `explanation`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub explanation: Option<String>,
    /// `plan`.
    pub plan: Vec<TurnPlanStep>,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
}

/// `ErrorNotification`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorNotification {
    /// `error`.
    pub error: TurnError,
    /// `threadId`.
    pub thread_id: String,
    /// `turnId`.
    pub turn_id: String,
    /// `willRetry`.
    pub will_retry: bool,
}
