use crate::CommandRecord;

/// Intended effect and scheduling priority of a Git command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandKind {
    /// Non-mutating repository inspection.
    Read,
    /// Local repository or worktree mutation.
    Mutation,
    /// Remote network operation.
    Network,
}

/// Records generated by a serialized mutation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MutationResult {
    /// Finished command records belonging to the mutation.
    pub records: Vec<CommandRecord>,
    /// Successful but notable Git output.
    pub warning: Option<String>,
}

/// Commit command flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct CommitOptions {
    /// Amend HEAD.
    pub amend: bool,
    /// Permit an empty tree change.
    pub allow_empty: bool,
    /// Add a Signed-off-by trailer.
    pub signoff: bool,
    /// Skip commit hooks.
    pub no_verify: bool,
}

/// Merge flags.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct MergeOptions {
    /// Require a fast-forward.
    pub ff_only: bool,
    /// Force creation of a merge commit.
    pub no_ff: bool,
    /// Apply changes without committing.
    pub squash: bool,
}

/// Reset mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResetMode {
    /// Move HEAD only.
    Soft,
    /// Reset HEAD and index.
    Mixed,
    /// Reset HEAD, index, and worktree.
    Hard,
}

/// Stash creation flags.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct StashOptions {
    /// Optional stash message.
    pub message: Option<String>,
    /// Include untracked paths.
    pub include_untracked: bool,
    /// Stash only staged changes.
    pub staged_only: bool,
    /// Keep index entries staged.
    pub keep_index: bool,
}

/// Fetch request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct FetchRequest {
    /// One remote; absent means the configured default.
    pub remote: Option<String>,
    /// Delete stale remote-tracking refs.
    pub prune: bool,
    /// Fetch all remotes.
    pub all: bool,
}

/// Pull request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PullRequest {
    /// Optional remote.
    pub remote: Option<String>,
    /// Optional remote branch.
    pub branch: Option<String>,
    /// Rebase local commits.
    pub rebase: bool,
    /// Require a fast-forward.
    pub ff_only: bool,
}

/// Push request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PushRequest {
    /// Optional remote.
    pub remote: Option<String>,
    /// Optional source branch.
    pub branch: Option<String>,
    /// Set upstream tracking.
    pub set_upstream: bool,
    /// Safely force only if the remote ref is unchanged.
    pub force_with_lease: bool,
    /// Unconditionally force.
    pub force: bool,
    /// Push tags in addition to the ref.
    pub tags: bool,
}
