[package]
name = "fleet-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
fleet-core = { path = "../fleet-core" }
fleet-proto = { path = "../fleet-proto" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
