[package]
name = "fleet-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
fleet-client = { path = "../fleet-client" }
fleet-core = { path = "../fleet-core" }
fleet-proto = { path = "../fleet-proto" }
serde.workspace = true
serde_json.workspace = true
