//! The `/bin/sh` launcher a fixture points `AgentKind::executable()` at.
//!
//! `fleet-daemon` does two things to a configured harness command that a `clap` subcommand cannot
//! absorb. It probes the binary first with `<command> --version` and refuses the harness when
//! that does not print a parseable version (`agents::harness::probe`), and it then appends the
//! vendor's own launch line — `app-server` for Codex, a dozen stream-json flags for Claude — to
//! whatever the command was (`agents::codex::mod`, `agents::claude::argv`). A `fleet-harness
//! agent …` command line would fail argument parsing on both counts.
//!
//! So a fixture writes this three-line shell script instead and configures *that* as the harness
//! command. It answers the probe, drops the vendor flags, and execs the real player. `/bin/sh`
//! rather than an interpreter the machine may not have, for exactly the reason
//! `fleet-daemon`'s `agents::harness::mockpeer` gives: a test suite that needs Python installed
//! is a test suite that silently skips on the machine that most needs it.

use std::path::{Path, PathBuf};

use super::Provider;

/// How far above the running executable `fleet-harness` is looked for: `target/<profile>/deps/`
/// up to `target/`, plus one level for a test binary run from a nested directory.
const BINARY_SEARCH_DEPTH: usize = 4;

/// Writes a launcher for `transcript` into `directory` and returns its path.
///
/// The returned path is the whole command line a `HarnessConfig` needs: it takes no arguments and
/// ignores the ones the adapter appends.
///
/// # Errors
///
/// Fails when this build's own executable cannot be located, when a path would have to be quoted
/// (a `'` in a run directory), or when the script cannot be written or made executable.
pub fn write_launcher(
    directory: &Path,
    provider: Provider,
    transcript: &Path,
) -> anyhow::Result<PathBuf> {
    let script = launcher_script(provider, transcript)?;
    std::fs::create_dir_all(directory)
        .map_err(|error| anyhow::anyhow!("create {}: {error}", directory.display()))?;
    let path = directory.join(format!("{}-agent.sh", provider.as_str()));
    std::fs::write(&path, script)
        .map_err(|error| anyhow::anyhow!("write {}: {error}", path.display()))?;
    make_executable(&path)?;
    Ok(path)
}

/// The launcher's `/bin/sh` source, for a caller that writes the file itself.
///
/// A fixture installs this under the *vendor's* name on the child `PATH` — shadowing `claude`
/// and `codex` is the whole point — so it needs the script rather than a file named after the
/// provider. [`write_launcher`] is the same script plus the write.
///
/// # Errors
///
/// Fails when this build's own executable cannot be located, or when a path would have to be
/// quoted (a `'` in a run directory).
pub fn launcher_script(provider: Provider, transcript: &Path) -> anyhow::Result<String> {
    let binary = shell_word(&harness_binary()?)?;
    let transcript = shell_word(transcript)?;
    Ok(format!(
        "#!/bin/sh\n\
         # Generated by fleet-harness: a scripted {provider} stand-in, not the vendor CLI.\n\
         # `fleetd` probes the binary with `--version` before it spawns a session, and appends\n\
         # the vendor's own launch flags afterwards; both are answered here.\n\
         for argument in \"$@\"; do\n\
         \x20 if [ \"$argument\" = \"--version\" ]; then\n\
         \x20   printf '%s\\n' '{version}'\n\
         \x20   exit 0\n\
         \x20 fi\n\
         done\n\
         exec {binary} agent --provider {provider} --transcript {transcript}\n",
        provider = provider.as_str(),
        version = provider.version_line(),
    ))
}

/// Where the `fleet-harness` binary is.
///
/// `current_exe` is the answer when the runner writes the launcher, but not when a test does:
/// there the running executable is `target/debug/deps/<test>-<hash>`, which has no `agent`
/// subcommand. So the override is honoured first and then the directory walk, which reaches
/// `target/debug/fleet-harness` from either place.
fn harness_binary() -> anyhow::Result<PathBuf> {
    if let Some(path) = std::env::var_os("FLEET_HARNESS_BIN") {
        let path = PathBuf::from(path);
        if path.is_file() {
            return Ok(path);
        }
    }
    let current = std::env::current_exe()
        .map_err(|error| anyhow::anyhow!("locate the running executable: {error}"))?;
    if current
        .file_name()
        .is_some_and(|name| name == "fleet-harness")
    {
        return Ok(current);
    }
    let mut directory = current.parent();
    for _level in 0..BINARY_SEARCH_DEPTH {
        let Some(candidate) = directory else { break };
        let binary = candidate.join("fleet-harness");
        if binary.is_file() {
            return Ok(binary);
        }
        directory = candidate.parent();
    }
    anyhow::bail!(
        "could not find the fleet-harness binary next to {}; build it with \
         `cargo build -p fleet-harness` or set FLEET_HARNESS_BIN",
        current.display()
    )
}

/// Renders a path as one single-quoted shell word.
///
/// A path carrying a `'` is refused rather than escaped: the adapter tokenizes the configured
/// command line itself (`agents::harness::process::command_parts`), so a cleverly quoted word
/// would survive this script and then be re-split there.
fn shell_word(path: &Path) -> anyhow::Result<String> {
    let rendered = path.to_string_lossy();
    if rendered.contains('\'') {
        anyhow::bail!(
            "{} cannot be launched from a scripted agent: the path contains a single quote",
            path.display()
        );
    }
    Ok(format!("'{rendered}'"))
}

#[cfg(unix)]
fn make_executable(path: &Path) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt as _;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
        .map_err(|error| anyhow::anyhow!("make {} executable: {error}", path.display()))
}

#[cfg(not(unix))]
fn make_executable(path: &Path) -> anyhow::Result<()> {
    anyhow::bail!(
        "the scripted agent launcher needs a POSIX shell; {} cannot be made executable here",
        path.display()
    )
}
